"""initial_schema

Revision ID: 651b935d2569
Revises: 
Create Date: 2026-02-11 06:27:58.251622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651b935d2569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('notification_preference', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('b2c_validated', sa.Boolean(), nullable=False),
    sa.Column('funding', sa.Text(), nullable=True),
    sa.Column('hq_city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('open_roles_count', sa.Integer(), nullable=False),
    sa.Column('last_researched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deep_dive_done', sa.Boolean(), nullable=False),
    sa.Column('deep_dive_content', sa.Text(), nullable=True),
    sa.Column('investors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lane IN (1, 2, 3)', name='ck_companies_lane_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('their_role', sa.String(length=255), nullable=True),
    sa.Column('connection_type', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('reached_out_date', sa.Date(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('referral_status', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("referral_status IN ('Identified', 'Reached_Out', 'Intro_Made', 'Referral_Submitted', 'Outcome')", name='ck_contacts_referral_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_calendar',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('post_url', sa.String(length=1000), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Planned', 'Drafted', 'Reviewed', 'Published')", name='ck_content_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('jobs_applied', sa.Integer(), nullable=False),
    sa.Column('connections_sent', sa.Integer(), nullable=False),
    sa.Column('comments_made', sa.Integer(), nullable=False),
    sa.Column('post_published', sa.Boolean(), nullable=False),
    sa.Column('networking_calls', sa.Integer(), nullable=False),
    sa.Column('referrals_asked', sa.Integer(), nullable=False),
    sa.Column('naukri_updated', sa.Boolean(), nullable=False),
    sa.Column('deep_dive_company', sa.String(length=255), nullable=True),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('key_win', sa.Text(), nullable=True),
    sa.Column('tomorrow_priorities', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('self_rating BETWEEN 1 AND 10', name='ck_daily_log_self_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_daily_log_user_date')
    )
    op.create_table('jd_keywords',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('frequency_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('in_profile_dna', sa.Boolean(), nullable=False),
    sa.Column('gap_flagged_date', sa.Date(), nullable=True),
    sa.Column('addressed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('jd_url', sa.String(length=1000), nullable=True),
    sa.Column('source_portal', sa.String(length=100), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resume_version', sa.String(length=100), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('referral_contact', sa.String(length=255), nullable=True),
    sa.Column('keywords_matched', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords_missing', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('interviewer_linkedin', sa.String(length=1000), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('interview_feedback', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Saved', 'Discovered', 'Analyzed', 'Applied', 'Screening', 'Interview_Scheduled', 'Interview_Done', 'Offer', 'Rejected', 'Withdrawn')", name='ck_jobs_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_dna',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('positioning_statement', sa.Text(), nullable=True),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_locations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_salary_range', sa.String(length=100), nullable=True),
    sa.Column('core_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tools_platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resume_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alumni_networks', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('career_narrative', sa.Text(), nullable=True),
    sa.Column('raw_resume_text', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('job_search_type', sa.String(length=50), nullable=True),
    sa.Column('lane_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_variants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('target_role_type', sa.String(length=255), nullable=True),
    sa.Column('customizations_made', sa.Text(), nullable=True),
    sa.Column('ats_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('week_end', sa.Date(), nullable=True),
    sa.Column('total_applied', sa.Integer(), nullable=False),
    sa.Column('total_connections', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('posts_published', sa.Integer(), nullable=False),
    sa.Column('interviews_scheduled', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('whats_working', sa.Text(), nullable=True),
    sa.Column('whats_not', sa.Text(), nullable=True),
    sa.Column('key_adjustment', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_metrics')
    op.drop_table('resume_variants')
    op.drop_table('refresh_tokens')
    op.drop_table('profile_dna')
    op.drop_table('jobs')
    op.drop_table('jd_keywords')
    op.drop_table('daily_log')
    op.drop_table('content_calendar')
    op.drop_table('contacts')
    op.drop_table('companies')
    op.drop_table('users')
    # ### end Alembic commands ###
